version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/ui
    schedule: { interval: weekly }
    groups:
      dev: { dependency-type: development }
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /packages/tokens
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
