#!/usr/bin/env node
/**
 * Generates every distributable from src/tokens.mjs. Zero dependencies.
 *
 *   dist/tokens.css            CSS custom properties (dark default, light via [data-theme="light"])
 *   dist/base.css              OPTIONAL global base (body colours, fonts, focus ring, selection)
 *   dist/tokens.json           flat + nested JSON, for tools and AI agents
 *   dist/index.{mjs,cjs,d.ts}  JS/TS: raw tokens, cssVar refs, legacy-kit adapter
 *   dist/tailwind-preset.{cjs,mjs,d.ts}
 */
import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as T from "../src/tokens.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
const PREFIX = "nex";

const hexToChannels = (hex) => {
  const h = hex.replace("#", "");
  if (!/^[0-9a-fA-F]{6}$/.test(h)) throw new Error(`Colour tokens must be 6-digit hex, got ${hex}`);
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)).join(" ");
};
const kebab = (s) => String(s).replace(/\./g, "_");

/* ---------------------------- CSS ---------------------------- */

const BRAND_NAMES = Object.keys(T.brands);
const brandSel = (b) => `[data-brand="${b}"]`;

function modeVars(brand, mode) {
  const m = T.brands[brand].modes[mode];
  const lines = [];
  for (const [k, v] of Object.entries(m.color)) lines.push(`  --${PREFIX}-color-${k}: ${hexToChannels(v)};`);
  for (const [k, v] of Object.entries(m.shadow)) lines.push(`  --${PREFIX}-shadow-${k}: ${v};`);
  return lines.join("\n");
}

function fontVars(brand) {
  const f = T.brands[brand].fontFamily;
  return ["sans", "mono", "display"].map((k) => `  --${PREFIX}-font-${k}: ${f[k].join(", ")};`).join("\n");
}

function staticVars() {
  const lines = [];
  for (const [k, v] of Object.entries(T.typography.fontWeight)) lines.push(`  --${PREFIX}-font-weight-${k}: ${v};`);
  for (const [k, [size, lh]] of Object.entries(T.typography.fontSize)) {
    lines.push(`  --${PREFIX}-text-${k}: ${size};`);
    lines.push(`  --${PREFIX}-leading-${k}: ${lh};`);
  }
  for (const [k, v] of Object.entries(T.typography.letterSpacing)) lines.push(`  --${PREFIX}-tracking-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.spacing)) lines.push(`  --${PREFIX}-space-${kebab(k)}: ${v};`);
  for (const [k, v] of Object.entries(T.radius)) lines.push(`  --${PREFIX}-radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.radiusRole)) lines.push(`  --${PREFIX}-radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.motion.duration)) lines.push(`  --${PREFIX}-duration-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.motion.easing)) lines.push(`  --${PREFIX}-ease-${k}: ${v};`);
  for (const [k, v] of Object.entries(T.zIndex)) lines.push(`  --${PREFIX}-z-${k}: ${v};`);
  return lines.join("\n");
}

// Non-default brands. Selectors are (0,2,0) so a nested data-theme section
// inside a branded page beats the brand's own (0,1,0) default.
function brandBlocks(b) {
  const B = brandSel(b);
  return `/* ---- brand: ${T.brands[b].label} — <html data-brand="${b}"> ---- */
${B} {
${fontVars(b)}
}

${B},
${B}[data-theme="dark"],
${B} [data-theme="dark"],
${B}.dark,
${B} .dark {
  color-scheme: dark;
${modeVars(b, "dark")}
}

${B}[data-theme="light"],
${B} [data-theme="light"],
${B}.light,
${B} .light {
  color-scheme: light;
${modeVars(b, "light")}
}
`;
}

const banner = `/* GENERATED by @thenexlabs/tokens — do not edit. Source: packages/tokens/src/tokens.mjs */`;

const tokensCss = `${banner}
/*
 * Colours are stored as space-separated RGB channels so alpha works:
 *   color: rgb(var(--${PREFIX}-color-fg));
 *   background: rgb(var(--${PREFIX}-color-accent) / 0.12);
 *
 * Brand:  default is ${T.brands[T.defaultBrand].label}. Others opt in with <html data-brand="...">
 *         (${BRAND_NAMES.filter((b) => b !== T.defaultBrand).join(", ")}).
 * Mode:   dark is the default. data-theme="light" (or class="light") swaps,
 *         on <html> or on any section (e.g. a light marketing band).
 * Importing this file changes NOTHING visually — it only defines variables.
 */
:root {
${staticVars()}
${fontVars(T.defaultBrand)}
}

/* ---- brand: ${T.brands[T.defaultBrand].label} (default) ---- */
:root,
[data-theme="dark"],
.dark {
  color-scheme: dark;
${modeVars(T.defaultBrand, "dark")}
}

[data-theme="light"],
.light {
  color-scheme: light;
${modeVars(T.defaultBrand, "light")}
}

${BRAND_NAMES.filter((b) => b !== T.defaultBrand).map(brandBlocks).join("\n")}`;

const baseCss = `${banner}
/*
 * OPTIONAL global base styles. Import AFTER tokens.css, once per app, when a
 * site is ready to let the design system own body colour, fonts and focus.
 */
html,
[data-theme],
.light,
.dark {
  background-color: rgb(var(--${PREFIX}-color-canvas));
  color: rgb(var(--${PREFIX}-color-fg));
  font-family: var(--${PREFIX}-font-sans);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
code, kbd, samp, pre, .nex-mono {
  font-family: var(--${PREFIX}-font-mono);
  font-variant-ligatures: none;
}
.nex-display {
  font-family: var(--${PREFIX}-font-display);
  letter-spacing: var(--${PREFIX}-tracking-tight);
}
.nex-data {
  font-family: var(--${PREFIX}-font-mono);
  font-variant-numeric: tabular-nums;
}
::selection {
  background-color: rgb(var(--${PREFIX}-color-accent) / 0.3);
  color: rgb(var(--${PREFIX}-color-fg));
}
:focus-visible {
  outline: none;
  box-shadow: var(--${PREFIX}-shadow-focus);
}
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}
`;

/* ---------------------------- JS ----------------------------- */

const colorNames = Object.keys(T.brands[T.defaultBrand].modes.dark.color);
const shadowNames = Object.keys(T.brands[T.defaultBrand].modes.dark.shadow);

const cssVar = {
  color: Object.fromEntries(colorNames.map((k) => [k, `rgb(var(--${PREFIX}-color-${k}))`])),
  shadow: Object.fromEntries(shadowNames.map((k) => [k, `var(--${PREFIX}-shadow-${k})`])),
  radius: Object.fromEntries([...Object.keys(T.radius), ...Object.keys(T.radiusRole)].map((k) => [k, `var(--${PREFIX}-radius-${k})`])),
  space: Object.fromEntries(Object.keys(T.spacing).map((k) => [k, `var(--${PREFIX}-space-${kebab(k)})`])),
  font: { sans: `var(--${PREFIX}-font-sans)`, mono: `var(--${PREFIX}-font-mono)`, display: `var(--${PREFIX}-font-display)` },
  duration: Object.fromEntries(Object.keys(T.motion.duration).map((k) => [k, `var(--${PREFIX}-duration-${k})`])),
  ease: Object.fromEntries(Object.keys(T.motion.easing).map((k) => [k, `var(--${PREFIX}-ease-${k})`])),
  z: Object.fromEntries(Object.keys(T.zIndex).map((k) => [k, `var(--${PREFIX}-z-${k})`])),
};

const tokensData = {
  palette: T.palette,
  typography: T.typography,
  spacing: T.spacing,
  radius: T.radius,
  radiusRole: T.radiusRole,
  motion: T.motion,
  zIndex: T.zIndex,
  breakpoints: T.breakpoints,
  defaultBrand: T.defaultBrand,
  brands: T.brands,
};

// Maps NEX semantics onto the old styled-components kit's `theme.colors` shape.
// Values are HEX (not CSS vars) because the old kit appends hex alpha, e.g. `${colors.text}99`.
function legacyKitColors(brand, mode) {
  const c = T.brands[brand].modes[mode].color;
  const n = T.palette.neutral;
  const dark = mode === "dark";
  return {
    failure: c.danger,
    primary: c.accent,
    primaryBright: c["accent-hover"],
    primaryDark: c["accent-text"],
    secondary: dark ? c.accent : c["accent-text"],
    success: c.success,
    warning: c.warning,
    binance: c.warning,
    overlay: n[1000],
    gold: "#FFC700",
    silver: "#B2B2B2",
    bronze: "#E7974D",
    background: c.canvas,
    backgroundDisabled: c.sunken,
    backgroundAlt: c.surface,
    backgroundAlt2: dark ? "rgba(0, 0, 0, 0.7)" : "rgba(255, 255, 255, 0.7)",
    cardBorder: c.line,
    contrast: c.fg,
    dropdown: c.raised,
    dropdownDeep: c.sunken,
    invertedContrast: c.canvas,
    input: c.sunken,
    inputSecondary: c.line,
    tertiary: c.raised,
    text: c.fg,
    textDisabled: c["fg-disabled"],
    textSubtle: c["fg-muted"],
    disabled: c["fg-disabled"],
    gradients: {
      bubblegum: `linear-gradient(180deg, ${c.surface} 0%, ${c.canvas} 100%)`,
      inverseBubblegum: `linear-gradient(180deg, ${c.canvas} 0%, ${c.surface} 100%)`,
      cardHeader: `linear-gradient(180deg, ${c.raised} 0%, ${c.surface} 100%)`,
      blue: `linear-gradient(180deg, ${c.raised} 0%, ${c.surface} 100%)`,
      violet: `linear-gradient(180deg, ${c.raised} 0%, ${c.surface} 100%)`,
      violetAlt: `linear-gradient(180deg, ${c.raised} 0%, ${c.surface} 100%)`,
      gold: "linear-gradient(180deg, #FFD800 0%, #FDAB32 100%)",
    },
  };
}
const legacy = Object.fromEntries(BRAND_NAMES.map((b) => [b, { dark: legacyKitColors(b, "dark"), light: legacyKitColors(b, "light") }]));

const jsBody = `
export const tokens = ${JSON.stringify(tokensData, null, 2)};
export const cssVar = ${JSON.stringify(cssVar, null, 2)};
const legacy = ${JSON.stringify(legacy, null, 2)};
/** CSS colour with alpha from a semantic token: withAlpha("accent", 0.12) */
export function withAlpha(name, alpha) {
  if (!(name in cssVar.color)) throw new Error("Unknown NEX colour token: " + name);
  return "rgb(var(--${PREFIX}-color-" + name + ") / " + alpha + ")";
}
/** Theme colours for the legacy @nextechlabs/nexdex-uikit (styled-components). */
export function toLegacyKitColors(mode = "dark", brand = "${T.defaultBrand}") {
  if (!legacy[brand]) throw new Error("Unknown brand: " + brand);
  if (!legacy[brand][mode]) throw new Error("mode must be 'dark' or 'light'");
  return JSON.parse(JSON.stringify(legacy[brand][mode]));
}
`;

const esm = `// GENERATED by @thenexlabs/tokens — do not edit.${jsBody}`;
const cjs = `"use strict";\n// GENERATED by @thenexlabs/tokens — do not edit.\n${jsBody
  .replace(/export const (\w+) =/g, "const $1 =")
  .replace(/export function (\w+)/g, "function $1")}
module.exports = { tokens, cssVar, withAlpha, toLegacyKitColors };
`;

const colorUnion = colorNames.map((k) => JSON.stringify(k)).join(" | ");
const dts = `// GENERATED by @thenexlabs/tokens — do not edit.
export type NexMode = "dark" | "light";
export type NexBrand = ${BRAND_NAMES.map((b) => JSON.stringify(b)).join(" | ")};
type NexModeTokens = { color: Record<NexColorToken, string>; shadow: Record<NexShadowToken, string> };
export type NexColorToken = ${colorUnion};
export type NexShadowToken = ${shadowNames.map((k) => JSON.stringify(k)).join(" | ")};
export declare const tokens: {
  palette: Record<string, Record<string, string>>;
  typography: {
    fontFamily: { sans: string[]; mono: string[]; display: string[] };
    fontWeight: Record<string, number>;
    fontSize: Record<string, [string, string]>;
    letterSpacing: Record<string, string>;
  };
  spacing: Record<string, string>;
  radius: Record<string, string>;
  radiusRole: Record<string, string>;
  motion: { duration: Record<string, string>; easing: Record<string, string> };
  zIndex: Record<string, number>;
  breakpoints: Record<string, string>;
  defaultBrand: NexBrand;
  brands: Record<NexBrand, { label: string; fontFamily: { sans: string[]; mono: string[]; display: string[] }; modes: Record<NexMode, NexModeTokens> }>;
};
export declare const cssVar: {
  color: Record<NexColorToken, string>;
  shadow: Record<NexShadowToken, string>;
  radius: Record<${[...Object.keys(T.radius), ...Object.keys(T.radiusRole)].map((k) => JSON.stringify(k)).join(" | ")}, string>;
  space: Record<string, string>;
  font: { sans: string; mono: string; display: string };
  duration: Record<${Object.keys(T.motion.duration).map((k) => JSON.stringify(k)).join(" | ")}, string>;
  ease: Record<${Object.keys(T.motion.easing).map((k) => JSON.stringify(k)).join(" | ")}, string>;
  z: Record<${Object.keys(T.zIndex).map((k) => JSON.stringify(k)).join(" | ")}, string>;
};
export declare function withAlpha(name: NexColorToken, alpha: number): string;
export declare function toLegacyKitColors(mode?: NexMode, brand?: NexBrand): Record<string, any>;
`;

/* ------------------------- Tailwind -------------------------- */

const twColors = Object.fromEntries(colorNames.map((k) => [k, `rgb(var(--${PREFIX}-color-${k}) / <alpha-value>)`]));

const presetBody = `
const colors = ${JSON.stringify(twColors, null, 2)};
const shadows = ${JSON.stringify(Object.fromEntries(shadowNames.map((k) => [k, `var(--${PREFIX}-shadow-${k})`])), null, 2)};
const radiusRole = ${JSON.stringify(Object.fromEntries(Object.keys(T.radiusRole).map((k) => [k, `var(--${PREFIX}-radius-${k})`])), null, 2)};
const fontSize = ${JSON.stringify(T.typography.fontSize, null, 2)};
const zIndex = ${JSON.stringify(Object.fromEntries(Object.entries(T.zIndex).map(([k, v]) => [k, String(v)])), null, 2)};
const duration = ${JSON.stringify(T.motion.duration, null, 2)};
const easing = ${JSON.stringify(T.motion.easing, null, 2)};
// Only 'caps' is added: Tailwind already owns tight/normal/wide.
const letterSpacing = { caps: "var(--${PREFIX}-tracking-caps)" };

/**
 * Build the NEX Tailwind preset.
 * Everything is added under theme.extend with NEW names, so adding the preset
 * to an existing site does not change any existing class — except fonts
 * (sans/mono), which you can defer with { fonts: false }.
 *
 * @param {{ fonts?: boolean, colorNamespace?: string }} [options]
 *   colorNamespace: nest colours, e.g. "nex" -> bg-nex-accent (use if names collide).
 */
function createNexPreset(options = {}) {
  const { fonts = true, colorNamespace } = options;
  const extend = {
    colors: colorNamespace ? { [colorNamespace]: colors } : colors,
    boxShadow: shadows,
    borderRadius: radiusRole,
    fontSize,
    zIndex,
    transitionDuration: duration,
    transitionTimingFunction: easing,
    letterSpacing,
  };
  if (fonts) {
    extend.fontFamily = {
      sans: ["var(--${PREFIX}-font-sans)"],
      mono: ["var(--${PREFIX}-font-mono)"],
    };
  }
  // 'display' is a new name, so it is always safe to add (marketing headlines).
  extend.fontFamily = { ...(extend.fontFamily || {}), display: ["var(--${PREFIX}-font-display)"] };
  return { theme: { extend } };
}
`;

const presetCjs = `"use strict";\n// GENERATED by @thenexlabs/tokens — do not edit.${presetBody}
const preset = createNexPreset();
module.exports = preset;
module.exports.createNexPreset = createNexPreset;
module.exports.default = preset;
`;
const presetEsm = `// GENERATED by @thenexlabs/tokens — do not edit.${presetBody}
const preset = createNexPreset();
export { createNexPreset };
export default preset;
`;
const presetDts = `// GENERATED by @thenexlabs/tokens — do not edit.
import type { Config } from "tailwindcss";
export interface NexPresetOptions { fonts?: boolean; colorNamespace?: string }
export declare function createNexPreset(options?: NexPresetOptions): Partial<Config>;
declare const preset: Partial<Config>;
export default preset;
`;

/* --------------------------- write --------------------------- */

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
const files = {
  "tokens.css": tokensCss,
  "base.css": baseCss,
  "tokens.json": JSON.stringify({ ...tokensData, cssVar }, null, 2) + "\n",
  "index.mjs": esm,
  "index.cjs": cjs,
  "index.d.ts": dts,
  "tailwind-preset.cjs": presetCjs,
  "tailwind-preset.mjs": presetEsm,
  "tailwind-preset.d.ts": presetDts,
};
for (const [name, body] of Object.entries(files)) writeFileSync(join(dist, name), body);
console.log(`@thenexlabs/tokens: wrote ${Object.keys(files).length} files to dist/`);
